apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  generation: 4
  name: new-pipeline
  namespace: redhat-ods-applications
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: "https://github.com/redhat-ai-services/ai-accelerator"
        - name: revision
          value: ""
        - name: refspec
          value: ""
        - name: submodules
          value: "true"
        - name: depth
          value: "1"
        - name: sslVerify
          value: "true"
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ""
        - name: sparseCheckoutDirectories
          value: ""
        - name: deleteExisting
          value: "true"
        - name: httpProxy
          value: ""
        - name: httpsProxy
          value: ""
        - name: noProxy
          value: ""
        - name: verbose
          value: "true"
        - name: gitInitImage
          value: "registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:66f219b4d54a41b945cb5715ecd1fbb5d25431cf8dad4b06914a4cdc65b298cc"
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: output
    - name: buildah
      params:
        - name: IMAGE
          value: CHANGEME***/redhat-ods-applications/custom-wb
        - name: BUILDER_IMAGE
          value: "registry.redhat.io/rhel8/buildah@sha256:b48f410efa0ff8ab0db6ead420a5d8d866d64af846fece5efb185230d7ecf591"
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: documentation/training_and_learning/custom_workbench/Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: "true"
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ""
        - name: PUSH_EXTRA_ARGS
          value: ""
        - name: SKIP_PUSH
          value: "false"
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: output
        #  CHANGEME Uncomment lines below if pushing to external registry
        # - name: dockerconfig
        #   workspace: docker-credentials
  workspaces:
    - name: output
    # CHANGEME Uncomment line below if pushing to external registry
    # - name: docker-credentials
